export const FETCH_AUDIT_LIST = 'FETCH_AUDIT_LIST';

export const FETCH_AUDIT_LIST_REQUEST = 'FETCH_AUDIT_LIST_REQUEST';

export const FETCH_AUDIT_LIST_SUCCESS = 'FETCH_AUDIT_LIST_SUCCESS';

export const FETCH_AUDIT_LIST_ERROR = 'FETCH_AUDIT_LIST_ERROR';

