export const FETCH_USER_LIST = 'FETCH_USER_LIST';

export const FETCH_USER_LIST_REQUEST = 'FETCH_USER_LIST_REQUEST';

export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS';

export const FETCH_USER_LIST_ERROR = 'FETCH_USER_LIST_ERROR';

export const UPDATE_USER = 'UPDATE_USER';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const UPDATE_USER_CLEAR = 'UPDATE_USER_CLEAR';

export const ROLE = {
  VIEWER: 'Viewer',
  ADMIN: 'Admin'
};
