
export const FETCH_CITIZEN = 'FETCH_CITIZEN';

export const FETCH_CITIZEN_REQUEST = 'FETCH_CITIZEN_REQUEST';

export const FETCH_CITIZEN_SUCCESS = 'FETCH_CITIZEN_SUCCESS';

export const FETCH_CITIZEN_ERROR = 'FETCH_CITIZEN_ERROR';

export const FETCH_ROLE = 'FETCH_ROLE';

export const FETCH_ROLE_REQUEST = 'FETCH_ROLE_REQUEST';

export const FETCH_ROLE_SUCCESS = 'FETCH_ROLE_SUCCESS';

export const FETCH_ROLE_ERROR = 'FETCH_ROLE_ERROR';

export const FETCH_HEALTH_FACILITIES = 'FETCH_HEALTH_FACILITIES';

export const FETCH_HEALTH_FACILITIES_REQUEST = 'FETCH_HEALTH_FACILITIES_REQUEST';

export const FETCH_HEALTH_FACILITIES_SUCCESS = 'FETCH_HEALTH_FACILITIES_SUCCESS';

export const FETCH_HEALTH_FACILITIES_ERROR = 'FETCH_HEALTH_FACILITIES_ERROR';

export const FETCH_EMBASSY = 'FETCH_EMBASSY';

export const FETCH_EMBASSY_REQUEST = 'FETCH_EMBASSY_REQUEST';

export const FETCH_EMBASSY_SUCCESS = 'FETCH_EMBASSY_SUCCESS';

export const FETCH_EMBASSY_ERROR = 'FETCH_EMBASSY_ERROR';

export const FETCH_PROVINCES = 'FETCH_PROVINCES';

export const FETCH_PROVINCES_REQUEST = 'FETCH_PROVINCES_REQUEST';

export const FETCH_PROVINCES_SUCCESS = 'FETCH_PROVINCES_SUCCESS';

export const FETCH_PROVINCES_ERROR = 'FETCH_PROVINCES_ERROR';

export const FETCH_DISTRICT = 'FETCH_DISTRICT';

export const FETCH_DISTRICT_REQUEST = 'FETCH_DISTRICT_REQUEST';

export const FETCH_DISTRICT_SUCCESS = 'FETCH_DISTRICT_SUCCESS';

export const FETCH_DISTRICT_ERROR = 'FETCH_DISTRICT_ERROR';

export const FETCH_SECTORS = 'FETCH_SECTORS';

export const FETCH_SECTORS_REQUEST = 'FETCH_SECTORS_REQUEST';

export const FETCH_SECTORS_SUCCESS = 'FETCH_SECTORS_SUCCESS';

export const FETCH_SECTORS_ERROR = 'FETCH_SECTORS_ERROR';

export const FETCH_CELLS = 'FETCH_CELLS';

export const FETCH_CELLS_REQUEST = 'FETCH_CELLS_REQUEST';

export const FETCH_CELLS_SUCCESS = 'FETCH_CELLS_SUCCESS';

export const FETCH_CELLS_ERROR = 'FETCH_CELLS_ERROR';

export const CREATE_NEW_USER = 'CREATE_NEW_USER';

export const CREATE_NEW_USER_REQUEST = 'CREATE_NEW_USER_REQUEST';

export const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS';

export const CREATE_NEW_USER_ERROR = 'CREATE_NEW_USER_ERROR';

export const CITIZEN_STORE_CLEAR = 'CITIZEN_STORE_CLEAR';

export const RESET_PASSWORD = 'RESET_PASSWORD';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const RESET_PASSWORD_CLEAR = 'RESET_PASSWORD_CLEAR';
