
export const CREATE_NEW_USER = 'CREATE_NEW_USER';

export const CREATE_NEW_USER_REQUEST = 'CREATE_NEW_USER_REQUEST';

export const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS';

export const CREATE_NEW_USER_ERROR = 'CREATE_NEW_USER_ERROR';

export const CREATE_NEW_USER_CLEAR = 'CREATE_NEW_USER_CLEAR';

export const GET_USER = 'GET_USER';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_USER_ERROR = 'GET_USER_ERROR';

export const EDIT_USER = 'EDIT_USER';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';

export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';

export const EDIT_USER_CLEAR = 'EDIT_USER_CLEAR';
