export const AUTH_ADMIN = 'AUTH_ADMIN';

export const AUTH_ADMIN_REQUEST = 'AUTH_ADMIN_REQUEST';

export const AUTH_ADMIN_SUCCESS = 'AUTH_ADMIN_SUCCESS';

export const AUTH_ADMIN_ERROR = 'AUTH_ADMIN_ERROR';

export const AUTH_ADMIN_CLEAR = 'AUTH_ADMIN_CLEAR';

export const EMAIL_EXIST = 'EMAIL_EXIST';

export const EMAIL_EXIST_REQUEST = 'EMAIL_EXIST_REQUEST';

export const EMAIL_EXIST_SUCCESS = 'EMAIL_EXIST_SUCCESS';

export const EMAIL_EXIST_ERROR = 'EMAIL_EXIST_ERROR';

export const EMAIL_EXIST_CLEAR = 'EMAIL_EXIST_CLEAR';

export const USER_PROFILE = 'USER_PROFILE';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';

export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';

export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';

export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';

export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const FORGOT_PASSWORD_CLEAR = 'FORGOT_PASSWORD_CLEAR';

export const GET_OTP = 'GET_OTP';

export const GET_OTP_REQUEST = 'GET_OTP_REQUEST';

export const GET_OTP_SUCCESS = 'GET_OTP_SUCCESS';

export const GET_OTP_ERROR = 'GET_OTP_ERROR';

export const GET_OTP_CLEAR = 'GET_OTP_CLEAR';
